version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    FRONTEND_REPO: <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/blog-frontend
    BACKEND_REPO: <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/blog-backend

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.us-east-1.amazonaws.com)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building the frontend Docker image...
      - docker build -t $FRONTEND_REPO:$IMAGE_TAG -f frontend-dockerfile .
      - echo Building the backend Docker image...
      - docker build -t $BACKEND_REPO:$IMAGE_TAG -f backend/Dockerfile backend

  post_build:
    commands:
      - echo Pushing the frontend image to ECR...
      - docker push $FRONTEND_REPO:$IMAGE_TAG
      - echo Pushing the backend image to ECR...
      - docker push $BACKEND_REPO:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"frontend-container","imageUri":"%s"},{"name":"backend-container","imageUri":"%s"}]' $FRONTEND_REPO:$IMAGE_TAG $BACKEND_REPO:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
