version: "3.9"

services:
  frontend:
    build:
      context: .
      args:
        REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
